== Einleitung

Im Zeitalter des Internet of Things (IoT) sind öffentliche Web APIs ein wichtiger Wettbewerbsfaktor. Der häufig genutzte Begriff API Economy rückt immer stärker in den Fokus. Sowohl õffentliche als interne APIs benötigen einen verständlichen Developer Guide, damit sie von Entwicklern eingesetzt werden können. Mit einer guten Dokumentation steht und fällt die Verbreitung einer Web API.
In der letzen Zeit sind viele Spezifikationsformate und Frameworks entstanden, die die Dokumentation einer HTTP-basierten API ermöglichen und vereinheitlichen sollen. Zu den bekanntesten Spezifikationsformaten gehören Swagger (nun OpenAPI Spezifikation[1]), RAML[2] oder API Blueprint[3]. 
All diese Projekte haben zum Ziel ein Spezifikationsformat zu entwickeln, dass maschinenlesbar ist, aber in erster Linie von Menschen erstellt werden können soll. Sie nutzen hierfür unterschiedliche Formate wie JSON, YAML oder Markdown. XML-basierte Formate wie die Web Application Description Language (WADL) eignen sich hierfür weniger.

Diese Spezifikiationsformate für sich alleine stellen aber nicht einen verständlichen Developer Guide dar, wie beispielweise der GitHub API Developer Guide[4]. Sie sollten um weitere Details ergänzt werden, wie beispielsweise echte HTTP Request und Response Beispiele, Code Beispiele oder CURL-Kommandos, mit denen die API direkt getestet werden kann.

Dieser Artikel zeigt wie man auf Basis einer Swagger Spezifikation mit Hilfe von Swagger2Markup und Asciidoctorj einen Developer Guide erstellen kann, der mit handgeschriebener Dokumentation kombiniert werden kann und sowohl offline (PDF-Format) als auch online (HTML-Format) lesbar ist.
