== Einleitung

Im Zeitalter des Internet of Things (IoT) sind öffentliche Web APIs ein wichtiger Wettbewerbsfaktor. Der häufig genutzte Begriff API Economy rückt immer stärker in den Fokus. Sowohl öffentliche als interne APIs benötigen einen verständlichen Developer Guide, damit sie von Entwicklern eingesetzt werden können. Mit einer guten Dokumentation steht und fällt die Verbreitung einer Web API.
In der letzen Zeit sind viele Spezifikationsformate und Frameworks entstanden, die die Dokumentation einer HTTP-basierten API ermöglichen und vereinheitlichen sollen. Zu den bekanntesten Spezifikationsformaten gehören Swagger (nun OpenAPI Spezifikation[1]), RAML[2] oder API Blueprint[3]. 
All diese Projekte haben zum Ziel ein Spezifikationsformat zu entwickeln, dass maschinenlesbar ist, aber in erster Linie von Menschen erstellt werden können soll. Sie nutzen hierfür unterschiedliche Formate wie JSON, YAML oder Markdown. XML-basierte Formate wie die Web Application Description Language (WADL) eignen sich hierfür weniger.

Diese Spezifikiationsformate für sich alleine stellen aber keinen verständlichen Developer Guide dar, wie beispielweise der GitHub API Developer Guide[4]. Sie sollten um weitere Informationen ergänzt werden, wie beispielsweise ein Tutorial mit echten HTTP Request und Response Beispielen, Code Beispielen oder CURL-Kommandos, mit denen die API direkt getestet werden kann.

Dieser Artikel ist in zwei Teile aufgeteilt. Teil 1 zeigt wie man auf Basis einer Swagger Spezifikation mit Hilfe der Open Source Projekte Swagger2Markup und Asciidoctorj einen Developer Guide erstellen kann, der mit handgeschriebener Dokumentation kombiniert werden kann und sowohl offline (PDF-Format) als auch online (HTML-Format) lesbar ist. Teil 2 zeigt wie man mit Hilfe des Open Source Projektes Springfox eine Swagger Spezifikation aus einer Spring Boot (MVC) Applikation generiert und HTTP Request und Response Beispiele mit Spring Rest Docs erstellt, die dann mit Hilfe von Swagger2Markup in einer Dokumentation vereint werden können.
