== CircuitBreaker, Retry und RateLimiter

Das Open-Source Project Javaslang-CircuitBreaker[2] ist eine leichtgewichtige Fehlertoleranz-Bibliothek, die von Netflix Hystrix inspiriert wurde, aber speziell für Funktionale Programming ausgelegt wurde. Leichtgewichtig, weil sie nur Javaslang und RxJava als Abhängigkeit hat, die wiederum keine weiteren Abhängigkeiten haben. Netflix Hystrix hingegen hat eine Abhängigkeit zu Netflix Archaius, welches weitere Abhängigkeiten zu Guava oder Apache Commons Configuration mit sich bringt.
Javaslang-CircuitBreaker stellt Funktionen höherer Ordnung (Higher-order functions) bereit, mit denen funktionale Schnittstellen, Lambda Ausdrücke und Methoden-Referenzen um einen CircuitBreaker erweitert werden können. Man kann diese Funktionen höherer Ordnung mit dem Decorator Pattern vergleichen, nur dass keine Klassen erstellt werden müssen. Neben dem CircuitBreaker werden auch Funktionen höherer Ordnung (Decorator) angeboten, um fehlgeschlagene Funktionen automatisch zu wiederholen (Retry) oder die Rate von Funktionsaufrufen zu limitieren (RateLimiter). Man kann mehrere dieser Decorator kombinieren.

=== CircuitBreaker

Listing 13 zeigt wie man einen Lambda Aufruf, der ein Backend aufruft, mit einem CircuitBreaker schützen und fehlgeschlagenen Aufrufe, die in einer IOException resultieren, automatisch wiederholen kann. Sowohl der CircuitBreaker als auch Retry haben viele Konfigurationsmöglichkeiten. Mit Hilfe von Try kann man einen Fallback ausführen, wenn der Aufruf trotz Wiederholungen fehlgeschlagen ist.

[source,java]
.Listing 13
----
// = CircuitBreaker Instanz mit default Konfiguration
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
    .recordFailure(throwable -> throwable instanceof IOException)
    .build();
CircuitBreaker circuitBreaker = CircuitBreaker.of("testName", circuitBreakerConfig);

// = Maximal 3 Wiederholungen und einem fixen Intervall zwischen den Wiederholungen
RetryConfig config = RetryConfig.custom()
    .maxAttempts(3)
    .waitDuration(Duration.ofMillis(100))
    .retryOnException(throwable -> throwable instanceof IOException)
    .build();
Retry retryContext = Retry.of("id", config);

// Dekoriere den Aufruf zum HelloWorldService
Try.CheckedSupplier<String> decoratedSupplier = Decorators
    .ofCheckedSupplier(() -> helloWorldService.sayHelloWorld("Robert"))
    .withCircuitBreaker(circuitBreaker)
    .withRetry(retryContext)
    .decorate();

Try<String> result = Try.of(supplier)
    .recover(throwable -> "Hello Recovery");
----

Der Javaslang-CircuitBreaker ist eine Zustandsmaschine mit den Zuständen: `CLOSED`, `OPEN` und `HALF_OPEN`. Der initiale Zustand ist CLOSED. Der CircuitBreaker speichert den Status (erfolgreich oder fehlgeschlagen) von Aufrufen in einem Ring Bit Buffer ohne rollendes Zeitfenster. Erfolgreiche Aufrufe werden als 1 Bit und fehlgeschlagene Aufrufe als 0 Bit gespeichert. Der Ring Bit Buffer hat eine konfigurierbare fixe Größe und speichert die Bits in einem long-Array. Das bedeutet, dass man in einem Array mit 16 long (64-bit) Werten den Status der letzten 1024 Aufrufen speichern kann. Diese Speicherform spart eine Menge Arbeitsspeicher. Der Vorteil an einem Ring Bit Buffer ohne rollendes Zeitfenster ist, dass man nicht vorab wissen muss mit welcher Frequenz das Backend aufgerufen wird, da keine Status gelöscht wird, wenn ein Zeitfenster abgelaufen ist. Wenn die Anzahl der fehlgeschlagenen Aufrufe einen konfigurierbaren Schwellwert überschreitet, wechselt der CircuitBreaker in den Zustand OPEN und weist weitere Aufrufe mit einer `CircuitBreakerOpenException` für einen konfigurierbaren Zeitintervall ab. Nach Ablauf des Zeitintervalls wechselt der CircuitBreaker in den Zustand HALF_OPEN und lässt eine konfigurierbare Anzahl an Aufrufen wieder durch. Wenn die meisten Aufrufe erfolgreich sind und der Schwellwert unterschritten wird, wechselt der CircuitBreaker wieder in den Zustand CLOSED, ansonsten wechselt er erneut in den Zustand OPEN und der Kreislauf beginnt aufs neue.

=== RateLimiter
Mit dem RateLimiter kann die Frequenz von Aufrufen zu einem Backend limitiert werden. Zum Beispiel kann limitiert werden, dass ein Backend nur einmal pro Sekunde aufgerufen werden darf, bevor der Aufruf mit einer `RequestNotPermittedException` abgewiesen. Siehe Listing 14.


[source,java]
.Listing 14
----
RateLimiterConfig config = RateLimiterConfig.custom()
    .limitRefreshPeriod(Duration.ofSeconds(1))
    .limitForPeriod(1)
    .build();
RateLimiter rateLimiter = RateLimiter.of("backendName", config);

// Dekoriere den Aufruf zum HelloWorldService
Try.CheckedSupplier<String> supplier = Decorators
    .ofCheckedSupplier(() -> helloWorldService.sayHelloWorld("Robert"))
    .withRateLimiter(rateLimiter)
    .decorate();
Try<String> result = Try.of(supplier);
----

=== Event stream

Sowohl CircuitBreaker, Retry als auch RateLimiter emittieren einen Event Stream mit Hilfe von RxJava, falls es einen Konsumenten gibt. Diese Events beinhalten Informationen, die für das Monitoring einer Programms interessant sind. Zum Beispiel die Antwortzeit von Aufrufen, die Fehler, die dazu führen, dass der CircuitBreaker getriggert wird oder Zustandswechsel. Listing 15 zeigt, wie man nur die Error-Events von einem CircuitBreaker konsumieren und in einem Circular Buffer ablegen kann, um nur die letzten 10 Events zu speichern. RxJava macht es mit Operatoren wie buffer oder window einfach, Events zwischenzuspeichern und diese in einem bestimmten Intervall stapelweise in eine Metriken-Datenbank wie InfluxDB oder Prometheus zu schreiben.

[source,java]
.Listing 15
----
CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("testName");
CircularEventConsumer<CircuitBreakerOnErrorEvent> circularEventConsumer = new CircularEventConsumer<>(10);
circuitBreaker.getEventStream()
    .filter(event -> event.getEventType() == Type.ERROR)
    .cast(CircuitBreakerOnErrorEvent.class)
    .subscribe(circularEventConsumer);

List<CircuitBreakerOnErrorEvent> bufferedEvents = circularEventConsumer.getBufferedEvents();
----

=== Metriken

Der CircuitBreaker bietet außerdem eine Schnittstelle an mit der Metriken, wie z.B. die Anzahl fehlgeschlagener Aufrufe oder die aktuelle Fehlerrate, überwacht werden können.

[source,java]
.Listing 16
----
CircuitBreaker.Metrics metrics = circuitBreaker.getMetrics();
float failureRate = metrics.getFailureRate();
int bufferedCalls = metrics.getNumberOfBufferedCalls();
int failedCalls = metrics.getNumberOfFailedCalls();
----
